version: '3.9'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: informes
    ports:
      - "33000:3306"
    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - riverspain 


  api:
    build: .
    restart: always
    container_name: microservicio-batidas
    ports:
      - "8000:8000"

    env_file:
       - .env  
    environment:
      # Actualiza la URL de conexión a la base de datos para que use el servicio "db"
      DATABASE_URL: "mysql+mysqlconnector://root:root@db/informes"
      MICROSERVICIOS_URL: "http://microservicio-gateway:8080/riverspain"
      EUREKA_SERVER: "http://microservicio-eureka:8761/eureka"
      EUREKA_APP_NAME: "msvc-batidas"
      INSTANCE_IP: microservicio-batidas
      INSTANCE_PORT: 8000
      HEALTH_CHECK_PATH: "/health"
      STATUS_PAGE_PATH: "/docs"


    volumes:
      - ./app:/app

    
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      db:
        condition: service_healthy
    networks:
      - riverspain

networks:
  networks:
  riverspain:
    external: true
    name: riverspain_network
  